extends "../Brain.gd"

enum Goal {
	GOAL_DESTROY_CARROTS,
	GOAL_KILL_PLAYER,
	GOAL_SURVIVE
}

enum Action {
	ACTION_ATTACK_CARROT,
	ACTION_ATTACK_PLAYER,
	ACTION_FLEE
}

func _init():
	add_goal(GOAL_DESTROY_CARROTS, 2)
	add_goal(GOAL_KILL_PLAYER, 2)
	add_goal(GOAL_SURVIVE, 2.1)

	add_action(ACTION_ATTACK_CARROT, {
		GOAL_DESTROY_CARROTS: -3,
		GOAL_KILL_PLAYER: 1,
		GOAL_SURVIVE: 1
	})

	add_action(ACTION_ATTACK_PLAYER, {
		GOAL_DESTROY_CARROTS: -1,
		GOAL_KILL_PLAYER: -3,
		GOAL_SURVIVE: 3
	})

	add_action(ACTION_FLEE, {
		GOAL_DESTROY_CARROTS: 1,
		GOAL_KILL_PLAYER: 1,
		GOAL_SURVIVE: -3
	})
